#!/usr/bin/python

#Install AP and Management Software
sudo apt install hostapd

sudo systemctl unmask hostapd
sudo systemctl enable hostapd

sudo apt install dnsmasq

sudo DEBIAN_FRONTEND=noninteractive apt install -y netfilter-persistent iptables-persistent



#Set up the Network Router
#1.Define the Wireless Interface IP Configuration
sudo nano /etc/dhcpcd.conf

#interface wlan0
    static ip_address=192.168.4.1/24
    nohook wpa_supplicant

#2.Enable Routing and IP Masquerading
sudo nano /etc/sysctl.d/routed-ap.conf

## Enable IPv4 routing
#net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo netfilter-persistent save

#2.Configure the DHCP and DNS services for the wireless network
sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
sudo nano /etc/dnsmasq.conf

interface=wlan0 # Listening interface
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
                # Pool of IP addresses served via DHCP
domain=wlan     # Local wireless DNS domain
address=/gw.wlan/192.168.4.1
                # Alias for this router