#!/bin/bash
LED BLUE FAST

cp /etc/dnsmasq.conf.hoc /etc/dnsmasq.conf
cp /etc/dhcpcd.conf.hoc /etc/dhcpcd.conf
sudo systemctl daemon-reload
sudo systemctl restart dhcpcd
sudo service dnsmasq start
sudo service hostapd restart

LED GREEN ON